services:
  - type: web
    name: ihsg-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api_final:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0