[theme]
primaryColor = "#67d9cb"
backgroundColor = "#0f1413"
secondaryBackgroundColor = "#181c21"
textColor = "#dee4e1"
font = "sans serif"

[client]
toolbarMode = "auto"
showErrorDetails = false
maxUploadSize = 200

[server]
port = 8501
headless = true
enableXsrfProtection = true
enableCORS = false
runOnSave = true

[logger]
level = "error"

[browser]
gatherUsageStats = false
